CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  auth_id VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) NOT NULL,
  provider VARCHAR(50) NOT NULL,
  user_uid VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS friends (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  friend_uid VARCHAR(255) NOT NULL
);
